### ISSUE TITLE
UnicodeDecodeError when building report

### ISSUE THREAD

**Issue by thulstrup** [tomgenoni/cssdig#1]
I get this error when running CSS Dig
`Attempting to reach URL...
Finding CSS at URL...
Building report...
Traceback (most recent call last):
  File "cssdig.py", line 262, in <module>
    .replace("{{ report_html }}", header_html + report_html);
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 26358: ordinal not in range(128)`

**Comment by tomgenoni** [comment]
Can you tell me the following:
1. What URL were you trying to run the report on?
2. What version of Python are you using (run `python -V` in the command line)
3. Were you able to run a report on any url, like http://apple.com ?

**Comment by thulstrup** [comment]
Sure:
1. I was trying my company's website http://designit.com. I couldn't get http://atomeye.com to work either
2. Python is version 2.7.2
3. Yes strangely enough http://apple.com does work

**Comment by tomgenoni** [comment]
Hmm, that is odd. I was able to run the report on your website — http://tinyurl.com/m3ozpme — sounds like an encode/decode problem with that html. I will play around with it and see if there's something I can suggest.

Can you try a couple things:
1. Remove the variable `header_html`, run the report.
2. Replace `header_html` and leave only `report_html`, run the report.
3. Can you comment out line 262 and see if the report completes? Should look like this:
   
    #.replace("{{ report_html }}", header_html + report_html);

**Comment by thulstrup** [comment]
Removing the header_html variable from line 262 fixes the problem.

**Comment by thulstrup** [comment]
Btw this is really really usefull. Great work :-)

**Comment by tomgenoni** [comment]
Thanks, glad you find it helpful. If you wanted to troubleshoot further you can comment out lines with variables between 234-244 and see which one is triggering the error.  That's where `header_html` is being constructed.

**Comment by thulstrup** [comment]
The `css_urls_list_good` variable in line 238 seems to be the problem.

UTF-8 encoding the url in line 137 (`css_urls_clean.append(u.encode('utf8'))`) does seem to fix the problem, but I've never used Pyhton before so I'm not sure if that's the correct way to do it :-)

**Comment by tomgenoni** [comment]
I just updated cssdig.py with your fix to both `css_urls_clean` and `css_urls_bad`. Could you try the updated script and see if it fixes this issue?

**Comment by thulstrup** [comment]
Just tried the updated script and it does fix the problem. Thanks.
